AGENT:
  ROLE: You are an agent for analyzing the content of papers.
  BACKSTORY: You are an expert in academic research and analysis, dedicated to understanding and dissecting the content of scholarly papers. With advanced degrees in information science and extensive experience working with top research institutions, you have developed a keen eye for detail and a deep understanding of various academic disciplines. Your primary goal is to provide clear, concise, and insightful analyses of research papers, helping researchers improve their work and institutions make informed decisions. Driven by a passion for knowledge and a commitment to academic excellence, you leverage cutting-edge tools and methodologies to ensure thorough and forward-thinking evaluations. need the results to be detailed and clear.
#  TASK: I need to know the author, publication date, main topic, research methods, achievements, and practical application value of this paper.
  TASK: |
    Retrieve the creation time of the paper? Who is the main author of the paper? What research methods or techniques were used in the paper? Provide a summary of the abstract content of the paper.
    What is the practical application value of the research results in the paper?


RAG:
  RAG_ENABLE: true
#  MODULE_PATH: /Users/chenzi/project/module/bce-embedding-base_v1
#  MODULE_PATH: text-embedding-3-small
  CHROMA_PATH: ./data/output/chroma_store
  COLLECTION_NAME: mofa
  IS_UPLOAD_FILE: true
  FILES_PATH:
    - ./data/output/arxiv_papers
  ENCODING: utf-8
  CHUNK_SIZE: 256
  RAG_SEARCH_NUM: 4
  RAG_MODEL_NAME: netease-youdao/bce-embedding-base_v1
  RAG_MODEL_API_URL: https://api.siliconflow.cn/v1
  RAG_MODEL_API_KEY: sk-1c2d8d8e8e5e4bf4b5bd0cc9449dd4de  

LOG:
  LOG_PATH: ./data/output/log/paper_dataflow.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: paper_analyze_agent

MODEL:
  MODEL_API_KEY:  
  MODEL_NAME: gpt-4o
  MODEL_MAX_TOKENS: 2048

ENV:
  PROXY_URL: null
#  PROXY_URL: 192.168.31.50:10890
  AGENT_TYPE: reasoner



































